### ISSUE TITLE
Some transforms don't work with distributed=True

### ISSUE THREAD

**Issue by jacobrosenthaldfci** [Dana-Farber-AIOS/pathml#130]
Dask.distributed uses pickling to send data across the cluster. However, this fails when objects are not pickleable. One place where this comes up in practice is TensorFlow models. This means that when a Pipeline contains a Transform that relies on a TF model, running the pipeline will fail when `distributed=True`. However, it gives a pretty cryptic error message. We should improve this by either: 

1. Find a way to make TF models compatible with dask distributed
2. Make a useful error message to tell the user what's going on if they try to use distributed preprocessing with an incompatible transform

**Comment by ryanccarelli** [comment]
Closed by #161
