### ISSUE TITLE
Set up github actions for packaging/distribution

### ISSUE THREAD

**Issue by ryanccarelli** [Dana-Farber-AIOS/pathml#145]
We need to add tests covering our pip installation and setup actions for new pypi releases.

**Comment by jacobrosenthaldfci** [comment]
We need to set up GH actions workflows to:
- publish new releases to PyPI (https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/)
- build and publish a Docker image (https://github.com/marketplace/actions/build-and-push-docker-images)

These should be triggered whenever we merge to master with a new tag, such as "v1.0.0" (https://stackoverflow.com/questions/66458906/how-to-conditionally-run-github-workflow-action-only-for-tags-made-on-specific-b)

**Comment by jacobrosenthaldfci** [comment]
Reopening this because we still need to set up a GH action for docker
