### ISSUE TITLE
Python-javabridge dependency causing pathml

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#156]
Having trouble installing. 

Specifically, in the python-javabridge dependency.

```

Collecting python-javabridge==4.0.0
  Downloading python-javabridge-4.0.0.tar.gz (1.3 MB)

 ERROR: Command errored out with exit status 1:
     command: /opt/conda/envs/tf-gpu/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7dozusc3/python-javabridge/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7dozusc3/python-javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s_xummyx
         cwd: /tmp/pip-install-7dozusc3/python-javabridge/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7dozusc3/python-javabridge/setup.py", line 412, in <module>
        ext_modules=ext_modules(),
      File "/tmp/pip-install-7dozusc3/python-javabridge/setup.py", line 96, in ext_modules
        java_home = find_javahome()
      File "/tmp/pip-install-7dozusc3/python-javabridge/javabridge/locate.py", line 133, in find_javahome
        java_bin = get_out(["bash", "-c", "type -p java"])
      File "/tmp/pip-install-7dozusc3/python-javabridge/javabridge/locate.py", line 130, in get_out
        raise Exception("Error finding javahome on linux: %s" % cmd)
    Exception: Error finding javahome on linux: ['bash', '-c', 'type -p java']
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jacobrosenthaldfci** [comment]
What do you get when you run `echo $JAVA_HOME` and `java -version`?

**Comment by ryanccarelli** [comment]
@surya-narayanan were you able to resolve this issue?

**Comment by dmbrundage** [comment]
I have been working on a docker image and I am having this same issue when I am installing pathml from PyPi.

`#13 275.9 Collecting python-javabridge==4.0.0
#13 275.9   Downloading python-javabridge-4.0.0.tar.gz (1.3 MB)
#13 276.5     ERROR: Command errored out with exit status 1:
#13 276.5      command: /root/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s9oy5545/python-javabridge_b4df77d29f52476bac4cd1aefd81e867/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s9oy5545/python-javabridge_b4df77d29f52476bac4cd1aefd81e867/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5rpndu4k
#13 276.5          cwd: /tmp/pip-install-s9oy5545/python-javabridge_b4df77d29f52476bac4cd1aefd81e867/
#13 276.5     Complete output (9 lines):
#13 276.5     Traceback (most recent call last):
#13 276.5       File "<string>", line 1, in <module>
#13 276.5       File "/tmp/pip-install-s9oy5545/python-javabridge_b4df77d29f52476bac4cd1aefd81e867/setup.py", line 412, in <module>
#13 276.5         ext_modules=ext_modules(),
#13 276.5       File "/tmp/pip-install-s9oy5545/python-javabridge_b4df77d29f52476bac4cd1aefd81e867/setup.py", line 142, in ext_modules
#13 276.5         library_dirs = [os.path.dirname(jvm_so)]
#13 276.5       File "/root/miniconda3/lib/python3.8/posixpath.py", line 152, in dirname
#13 276.5         p = os.fspath(p)
#13 276.5     TypeError: expected str, bytes or os.PathLike object, not NoneType
#13 276.5     ----------------------------------------
#13 276.5 WARNING: Discarding https://files.pythonhosted.org/packages/58/5c/bfcc52002c9dfe5fe3bd067783243ab0130f59f757b0517f62f1ba7e88ea/python-javabridge-4.0.0.tar.gz#sha256=9fd9c85e6a32f4edd9fff659d387cbf4c1c91fde9fe3670e4f6d37d79eb6200f (from https://pypi.org/simple/python-javabridge/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#13 276.5 INFO: pip is looking at multiple versions of pydicom to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of pre-commit to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of pip to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of openslide-python to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of opencv-contrib-python to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of h5py to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of distributed to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of dask to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of dask[distributed] to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of anndata to determine which version is compatible with other requirements. This could take a while.
#13 276.5 INFO: pip is looking at multiple versions of pathml to determine which version is compatible with other requirements. This could take a while.
#13 276.5 ERROR: Could not find a version that satisfies the requirement python-javabridge==4.0.0 (from python-bioformats) (from versions: 4.0.0, 4.0.1, 4.0.2, 4.0.3)
#13 276.5 ERROR: No matching distribution found for python-javabridge==4.0.0`

**Comment by dmbrundage** [comment]
This was an issue with having JAVA_HOME set.

**Comment by rahit** [comment]
```
rahit@mac ~ echo $JAVA_HOME
/opt/homebrew/envs/py38/lib/jvm
rahit@mac ~ java --version
openjdk 11.0.25 2024-10-15 LTS
OpenJDK Runtime Environment Zulu11.76+21-CA (build 11.0.25+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.76+21-CA (build 11.0.25+9-LTS, mixed mode)
rahit@mac ~ mamba list openjdk
List of packages in environment: "/opt/homebrew/envs/py38"

  Name     Version  Build       Channel    
─────────────────────────────────────────────
  openjdk  11.0.25  h7c160ba_1  conda-forge
```
`pip install pathml` fails with following error:
```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-javabridge
  Running setup.py clean for python-javabridge
Failed to build python-javabridge
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (python-javabridge)
```
