### ISSUE TITLE
h5manager can't write new tiles to disk

### ISSUE THREAD

**Issue by MohamedOmar2020** [Dana-Farber-AIOS/pathml#157]
Hello, 
I installed the new release and now I am having an issue with slidedata.run. This is the command I used:

`slidedata.run(pipe, distributed = False, tile_size= (6392, 6617), tile_pad=False, overwrite_existing_tiles=True)
`

With this tile_size, the image should be divided into 9 tiles. The processing of the first tile is fine but it seems there is a problem with the subsequent tiles especially writing/updating the count matrix.

> 2021-08-06 01:45:11.435013: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
> /Users/mohamedomar/.local/lib/python3.8/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
>   def watershed(image, markers=None, connectivity=1, offset=None, mask=None,
> /Users/mohamedomar/.local/lib/python3.8/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
>   def watershed(image, markers=None, connectivity=1, offset=None, mask=None,
> /Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
>   warnings.warn("Transforming to str index.", ImplicitModificationWarning)
> /Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/anndata/_io/h5ad.py:58: FutureWarning: The `force_dense` argument is deprecated. Use `as_dense` instead.
>   warn(
> /Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/anndata/_core/anndata.py:1192: FutureWarning: is_categorical is deprecated and will be removed in a future version.  Use is_categorical_dtype instead
>   if is_string_dtype(df[key]) and not is_categorical(df[key])
>  storing 'coords' as categorical
>  storing 'slice' as categorical
>  storing 'tile' as categorical
> /Users/mohamedomar/.local/lib/python3.8/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
>   def watershed(image, markers=None, connectivity=1, offset=None, mask=None,
> /Users/mohamedomar/.local/lib/python3.8/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
>   def watershed(image, markers=None, connectivity=1, offset=None, mask=None,
> /Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/anndata/_core/anndata.py:119: ImplicitModificationWarning: Transforming to str index.
>   warnings.warn("Transforming to str index.", ImplicitModificationWarning)
> Traceback (most recent call last):
>   File "/Users/mohamedomar/opt/anaconda3/envs/pathml2/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-12-88176dcd05cf>", line 1, in <module>
>     slidedata.run(pipe, distributed = False, tile_size= (6392, 6617), tile_pad=False, overwrite_existing_tiles=True)
>   File "/Users/mohamedomar/Documents/Research/Tutorials/pathml2/pathml/core/slide_data.py", line 320, in run
>     self.tiles.add(tile)
>   File "/Users/mohamedomar/Documents/Research/Tutorials/pathml2/pathml/core/tiles.py", line 81, in add
>     self.h5manager.add_tile(tile)
>   File "/Users/mohamedomar/Documents/Research/Tutorials/pathml2/pathml/core/h5managers.py", line 246, in add_tile
>     self.counts = self.counts.to_memory()
> AttributeError: 'AnnData' object has no attribute 'to_memory'

**Comment by ryanccarelli** [comment]
@MohamedOmar2020 Can you try 
```
conda install --upgrade anndata
```

**Comment by MohamedOmar2020** [comment]
Ok, I updated it. Still waiting to see if it works.

**Comment by MohamedOmar2020** [comment]
@ryanccarelli it worked, thanks!.
