### ISSUE TITLE
colab badge

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#172]
can we add the "open in colab" badge to the examples?

couple of issues at preset time:
1. colab does not have py3.8 -- which seems addressed in https://github.com/ancillaryfactory/Colab-ML-starter/blob/master/Python_3_8_Starter.ipynb
2. installation of pathml is somewhat broken: `!apt-get -qq install -y openslide-tools g++ gcc libblas-dev liblapack-dev openjdk-8-jdk-headless; pip install pathml`

While the [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Dana-Farber-AIOS/pathml/blob/master/examples/pathml_gallery.ipynb) button at the top of the ReadTheDocs examples would be awesome, I'm not sure we can easily deliver it.

NOTE: the button above imports the code into a temporary colab env but it does not work.

**Comment by jacobrosenthaldfci** [comment]
Maybe [binder](https://mybinder.readthedocs.io/en/latest/introduction.html) would be a better fit?
Looks like they have support for custom environments using environment.yml and possibly also docker.
Will look into this further

**Comment by jacobrosenthaldfci** [comment]
Closing this as low priority. We can reopen in the future if needed

**Comment by Dana-Farber** [comment]
https://stackoverflow.com/questions/55835318/how-to-create-and-use-a-custom-openai-gym-environment-on-google-colab?rq=1
