### ISSUE TITLE
View on GitHub button for the examples

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#173]
Can we add the "View on GitHub" button at the top and bottom of the examples?

**Comment by jacobrosenthaldfci** [comment]
I can add this next week. It would look something like: 

<a href="https://github.com/Dana-Farber-AIOS/pathml/blob/master/examples/pathml_gallery.ipynb">
        <img src="https://img.shields.io/badge/View-on%20GitHub-lightgrey?logo=github" /></a>

**Comment by jacobrosenthaldfci** [comment]
Closed in #185
