### ISSUE TITLE
Align the pypi intro page and the github readme

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#188]
Content of https://pypi.org/project/pathml/ should reflect what we have in https://github.com/Dana-Farber-AIOS/pathml/blob/master/README.md

Can we automate this alignment so that pypi is always sync'ed and that github is the "single source of truth" that is then propagated to pypi, conda, and other reposositories?

**Comment by jacobrosenthaldfci** [comment]
Yes, the GitHub repo is the ground truth, PyPI is updated with the GitHub readme every time we make a new release. We just pushed v1.0.1 today so it is up to date now
