### ISSUE TITLE
Homebrew not 'brewing' Openslide: No formulae found in taps

### ISSUE THREAD

**Issue by antoniofaneite** [Dana-Farber-AIOS/pathml#198]
If you're installing openslide external dependency with homebrew, using 'brew install openslide' you might get the error:

`No formulae found in taps`

In such case, run:

`git -C $(brew --repository homebrew/core) checkout master`

or

`git -C $(brew --repository homebrew/core) reset --hard HEAD.`

Then, run:

`brew install openslide`

The problem should be resolved.

**Comment by jacobrosenthaldfci** [comment]
Thank you, @antoniofaneite !
