### ISSUE TITLE
install in windows

### ISSUE THREAD

**Issue by Alan-Py** [Dana-Farber-AIOS/pathml#214]
can it install in win ?

**Comment by jacobrosenthaldfci** [comment]
Hi @Alan-Py , this is not something we have tested - do you run into problems when trying to install?
One option may be to use windows subsystem for linux

**Comment by ryanccarelli** [comment]
Another option is to install miniconda https://docs.conda.io/en/latest/miniconda.html and to follow the conda installation option in anaconda prompt https://github.com/Dana-Farber-AIOS/pathml#installation-option-2-clone-repo-and-install-from-source

**Comment by Alan-Py** [comment]
thank you,I get it.

Ryan Carelli ***@***.***> 于2021年10月31日周日 上午1:14写道：
