### ISSUE TITLE
Save slides from SlideDataset in pipeline

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#219]
**Describe the bug**
If I have a pipeline that is running on a massive dataset, is there a way to save the outputs of processed slides intermittently?  So that I don't have to wait for the whole pipeline to finish running before I can run .save on the SlideData/SlideDataset?

**Expected behavior**
have a .save transform that is applied to a SlideData object as the last transform of a pipeline

**Comment by jacobrosenthaldfci** [comment]
I see your point. 

I think the place to put this would be after each slide is processed: https://github.com/Dana-Farber-AIOS/pathml/blob/bfbe277b0ad9396c19071af751b4dfdfe42374f3/pathml/core/slide_dataset.py#L54-L57

You could write a class that inherits from `SlideDataset` and has the modification that you want, here's some pseudocode:

````python

class SlideDatasetModified(SlideDataset):
    def __init__(self, *args, **kwargs):
        super().__init__(self, *args, **kwargs)

    def run_and_write(self, pipeline, save_dir, client=None, distributed=True, **kwargs):
        """
        Copied from SlideDataset.run() with additional slide.write step
        Runs a preprocessing pipeline on all slides in the dataset
        Args:
            pipeline (pathml.preprocessing.pipeline.Pipeline): Preprocessing pipeline.
            client: dask.distributed client
            distributed (bool): Whether to distribute model using client. Defaults to True.
            kwargs (dict): keyword arguments passed to :meth:`~pathml.core.slide_data.SlideData.run` for each slide
        """
        # run preprocessing
        if client is None and distributed:
            client = dask.distributed.Client()
        for slide in self.slides:
            slide.run(
                pipeline=pipeline, client=client, distributed=distributed, **kwargs
            )
            # write slides as they are processed
            slide.write(f"save_dir/{slide.name}.h5path")
````

**Comment by surya-narayanan** [comment]
Would it be in your books to include this run_and_write function in the core API?

**Comment by jacobrosenthaldfci** [comment]
I think it would be better to just add a new parameter to `run()` instead of making a whole new method. As long as the default value is to not write, it should keep backwards compatibility.
Would you want to take the lead on adding that and opening a PR? It would only be a few lines of code

**Comment by surya-narayanan** [comment]
Sure, I can do that.
