### ISSUE TITLE
Kernel dies on apple M1

### ISSUE THREAD

**Issue by saramoein372** [Dana-Farber-AIOS/pathml#220]
Hello,

I have a question about running pathml preprocessing pipeline.

I could install pathml on jupyter, however after running the pipeline code:
pipe = Pipeline([
    CollapseRunsCODEX(z=0),
    SegmentMIF(model='mesmer', nuclear_channel=0, cytoplasm_channel=29, image_resolution=0.377442),
    QuantifyMIF(segmentation_mask='cell_segmentation')
])

I get the error of "kernel died and then restart automatically".

I did a search and understood some packages like "tensorflow", caused the kernel dies.

I am not sure why in the "pipeline" code this is happening? Do you have any comment about it? And what is the solution?

Thanks,
Sara

**Comment by jacobrosenthaldfci** [comment]
Hi Sara, that's an error that I haven't seen before. From [this thread](https://stackoverflow.com/questions/47022997/jupyter-the-kernel-appears-to-have-died-it-will-restart-automatically) it looks like other people have seen the same thing. I think this seems like an environment configuration problem - maybe try the solutions mentioned in the stackoverflow about reinstalling numpy and other packages?

**Comment by jacobrosenthaldfci** [comment]
Closing this for now, feel free to reopen if needed
