### ISSUE TITLE
BoxBlur pipeline doesn't distribute work

### ISSUE THREAD

**Issue by KarthikNair1** [Dana-Farber-AIOS/pathml#222]
**Describe the bug**
When executing a pipeline with a single BoxBlur transform, work isn't distributed to speed up processing.

**To Reproduce**

```
from pathml.processing import Pipeline, BoxBlur
from pathml.core import HESlide, SlideDataset, SlideData, types

fp = '/mnt/disks/disk_use/LUAD/LUAD_svs/TCGA-S2-AA1A-01Z-00-DX1.4B5D5FAE-8305-4D2D-B245-584589352886.svs'
wsi_example = HESlide(fp, backend = 'openslide')

test_pipeline = Pipeline(
    [
        BoxBlur(kernel_size = 15)
    ]
)

cluster = LocalCluster(n_workers=10)
client = Client(cluster)
dataset.run(test_pipeline, distributed = True, client = client)
```

Upon monitoring threads using ```htop``` in terminal, no more than 1 thread at a time is being utilized. 

As a further test, a custom transform was defined that simply prints out the coordinates of the tile being processed. The result was that tiles were printed in linear order, indicating that distribution didn't happen for this custom function either.

```
class Test(Transform):
    """Box (average) blur kernel."""
    def __init__(self):
        return

    def F(self, image):
        return
    def apply(self, tile):
        print(tile.coords)
        return

pipeline2 = Pipeline(
    [
        Test()
    ]
)

wsi_example.run(pipeline2, distributed = True, client = client)
```

**Expected behavior**
More than 1 core should be utilized, both for BoxBlur and for Test(). Instead, only 1 core was utilized.

**Screenshots**
Screenshot of htop during pipeline run:

<img width="1334" alt="Screen Shot 2021-11-05 at 4 10 35 PM" src="https://user-images.githubusercontent.com/43316987/140572616-1d83519a-d4db-4d05-b7b0-e5d47342aaf3.png">

**Additional context**

**Comment by jacobrosenthaldfci** [comment]
Thanks Karthik!

So I tried it out on my machine but wasn't able to reproduce what you're seeing. Here's htop before running the pipeline:

![before pipeline running](https://user-images.githubusercontent.com/53529525/140581221-b2ba29f7-6057-4812-8b1c-023ce8b8c11b.png)

And here's htop during running the pipeline:

![during distributed pipeline running](https://user-images.githubusercontent.com/53529525/140581260-a70887f6-bfce-4f04-9950-781ab5adf98d.png)

At least on my laptop, it does seem to be using all cores.

Another thing to consider is that distributing computation introduces an overhead, i.e. time needed to spin up the cluster, send data to the workers, retrieve processed data from the workers, manage the workers, etc. So if the computation itself is pretty simple, the overhead from distributing can actually make the overall runtime worse. This is exactly what I saw when running the simple pipeline in your example:

![Screen Shot 2021-11-05 at 5 38 53 PM](https://user-images.githubusercontent.com/53529525/140581585-8a56ab44-a51d-4593-926f-5282501261c0.png)

The final note is that the bottleneck of performance seems to be writing the tiles into the h5 array (see [here](https://github.com/Dana-Farber-AIOS/pathml/pull/200#issuecomment-933632090) for a profile), and that can't be distributed, so depending on when you look at the htop, you may not see all the cores being used if for example it is in the part of the runtime where it is just putting all the processed tiles into h5.

**Comment by jacobrosenthaldfci** [comment]
By the way I tried your second test, and nothing printed at all.... which is what I expect, given that the print function is called on the worker, not on the main process, and you don't see the stdout from the workers (see https://github.com/dask/distributed/issues/2033)
![Screen Shot 2021-11-05 at 5 54 51 PM](https://user-images.githubusercontent.com/53529525/140582903-96c53b62-ee2d-4761-870b-ba54bbae3371.png)

**Comment by jacobrosenthaldfci** [comment]
Sorry if this is not super helpful. What you are seeing may be related to the details of how you have you dask client set up on your machine.

**Comment by jacobrosenthaldfci** [comment]
Update: when I shut down my cluster, it spat out all the print statements:

![Screen Shot 2021-11-05 at 5 58 57 PM](https://user-images.githubusercontent.com/53529525/140583233-69bc0c73-7391-485d-9d0a-75d549ccd0fc.png)

They do not appear to be in order, suggesting that they were submitted to the client as expected

**Comment by ryanccarelli** [comment]
Please feel free to reopen if you have any further questions
