### ISSUE TITLE
Overlapping tiles

### ISSUE THREAD

**Issue by jacobrosenthaldfci** [Dana-Farber-AIOS/pathml#223]
We need to modify the h5manager to support overlapping tiles. 

This will require changing a few things:
- The size of the h5path array needs to be determined based on total number of tiles, not just the shape of the original image.
- Function to convert between image coordinates and h5 coordinates
- May need to add a `stride` field to h5path metadata
- Need to be careful when working with the two coordinate systems, and specify which is which in the h5path format, between the tile key in the "tiles/" group and `coords` attribute within each tile's metadata.
- How do we handle masks with overlapping tiles? It could make sense to have masks the same shape as the original image, or to have one mask per tile.

This should be a relatively simple fix, just adding a layer of converting between tile coords and h5 coords before getting or setting anything in the h5 array.

**Comment by ryanccarelli** [comment]
Closed with #231
