### ISSUE TITLE
adding the Otsu threshold to SegmentMIF

### ISSUE THREAD

**Issue by saramoein372** [Dana-Farber-AIOS/pathml#227]
Hi there,

Thanks for your helps.

I have a question about segmentation using SegmentMIF. I am using below code for segmenting my image, to extract the intensity from the images. 
slidedata_image = VectraSlide('imagefile.tif')
pipe = Pipeline([
    CollapseRunsVectra(),
    #HistogramEqualization(),
    SegmentMIF(model='mesmer', nuclear_channel=0, cytoplasm_channel=7, image_resolution=0.5),
    QuantifyMIF(segmentation_mask='cell_segmentation')
])

adata_image = slidedata_image.counts.to_memory()

However I am not happy about the segmentation results. I am thinking in my gray color images the gray and white intensities are not separated correctly.
I am thinking if I could use a filter (something like an Otsu thresholding) in my current pipeline, then I could get much better results.

Is there anyway to make my segmentation better in this pipeline? I am reading the github codes, but not successful to find the correct way to add more filtering to this pipeline.

I appreciate your help and support!

Thanks,
Sara

**Comment by ryanccarelli** [comment]
Hi Sara,

We have an implementation of Otsu here https://pathml.readthedocs.io/en/latest/api_preprocessing_reference.html#pathml.preprocessing.BinaryThreshold that you can add to your pipeline. Maybe followed by foreground detection https://pathml.readthedocs.io/en/latest/api_preprocessing_reference.html#pathml.preprocessing.ForegroundDetection.

Regarding segmentation quality, please make sure you are passing the appropriate channels. From the paper (https://authors.library.caltech.edu/108281/1/2021.03.01.431313v1.full.pdf):
```
We used the PanopticNet architecture and TissueNet to create Mesmer, a deep learning pipeline for accurate
nuclear and whole-cell segmentation of tissue data. Mesmer’s PanopticNet model contains four semantic
heads (two for nuclear segmentation and two for whole-cell segmentation) that are attached to a common
backbone and FPN. The input to Mesmer is a nuclear image (e.g. DAPI) to define the nucleus of each cell
and a membrane or cytoplasm image (e.g. CD45 or E-cadherin) to define the shape of each cell (Figure
2a). These inputs are normalized56 (to improve robustness), tiled into patches of fixed size (to allow
processing of images with arbitrary dimensions), and then fed to the PanopticNet model. The model outputs
are then untiled57 to produce predictions for the centroid and boundary of every nucleus and cell in the
image. The centroid and boundary predictions are used as inputs to a watershed algorithm58 to create the
final instance segmentation mask for each nucleus and each cell in the image (Methods). 
```

It is possible that the membrane/cytoplasm channel you are using is not ubiquitous in every cell. If it isn't staining a cell then the model will have trouble with the segmentation. I've had good results using auto-fluorescence as a stand-in for the membrane/cytoplasm channel when good markers aren't available in the panel. Ideally you would use as general a cell membrane marker as possible (like NaKATPase), but I understand that if you are working with Vectra images the limitation to 7 or 8 channels might make this difficult to include

Ryan

**Comment by ryanccarelli** [comment]
Please reopen this issue if you have any other questions

**Comment by surya-narayanan** [comment]
Hi, are these pipelines viable for non-H&E modalities? Thanks in advance.

**Comment by jacobrosenthaldfci** [comment]
Yes, this is all for non-H&E. From the snippet Ryan posted above, it requires as input a nuclear marker channel and a cytoplasm marker channel, which you won't have for brightfield H&E images (which will typically only have RGB channels)

**Comment by saramoein372** [comment]
Thanks Jacob
