### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by ryanccarelli** [Dana-Farber-AIOS/pathml#230]
Currently we have print statements that should be handled by logging.

**Comment by BeeGass** [comment]
To create a list to reference in the future:
- [ ] development mode that can be enabled to see pathml specific logs
- [ ] be able to switch from terminal outputted logs and log file
  - [ ] logging of user hardware
- [ ] logging distributed computing through DASK's API 

Please let me know what other things I missed. I know there are class specific things that should take precedent.

**Comment by jacob-rosenthal** [comment]
Looks good. Lets also add:

- [ ]  logging configuration details of dask cluster when running pipelines with distributed=True (number of workers, resources per worker, worker configurations, etc. etc.)

**Comment by BeeGass** [comment]
- [ ] log and better error handle when environment variables are not found or have not been imported.

**Comment by jacob-rosenthal** [comment]
Added in #304
