### ISSUE TITLE
Unable to open tile object (object 'array' doesn't exist)

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#243]
**Describe the bug**
Unable to access tile array from `TileDataset.__getitem__() `
`KeyError: "Unable to open object (object 'array' doesn't exist)"`

**To Reproduce**
Traceback:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_4463/806735975.py in <module>
----> 1 tile_dataset.__getitem__(0)

~/pathml/pathml/ml/dataset.py in __getitem__(self, ix)
     54         ### this part copied from h5manager.get_tile()
     55         tile_image = self.h5["tiles"][str(k)]["array"][:]
---> 56 
     57         # get corresponding masks if there are masks
     58         if "masks" in self.h5["tiles"][str(k)].keys():

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

/opt/conda/envs/wtf/lib/python3.8/site-packages/h5py/_hl/group.py in __getitem__(self, name)
    286                 raise ValueError("Invalid HDF5 object reference")
    287         else:
--> 288             oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    289 
    290         otype = h5i.get_type(oid)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5o.pyx in h5py.h5o.open()

KeyError: "Unable to open object (object 'array' doesn't exist)"
```

**Expected behavior**
Should be able to access the tile array object. I created the h5 file with the following code:

```
slidename = < Path to Slide >
slide = SlideData(slide_name, backend = "bioformats", slide_type = types.Vectra)
slide.write(f'/parent_directory/{slide.name}.h5')
```

**Comment by jacobrosenthaldfci** [comment]
You can inspect what's happening in the h5 file with something like:

```python
h5 = h5py.File(tile_dataset.file_path, "r")
tile_keys = list(h5["tiles"].keys())
print(tile_keys) # what do you see here?
k = tile_keys[0]
tile_group = h5["tiles"][str(k)]
print(tile_group)
````

What do you see from these? This might help diagnose the problem.

Are you able to reproduce this on `tests/testdata/small_vectra.qptiff`?

Thanks!

**Comment by surya-narayanan** [comment]
Thank you for the prompt response. 

Tried what you suggested, this looks good to me - 
![image](https://user-images.githubusercontent.com/17240858/144659823-923be999-35da-407e-9dd3-52a651f13d84.png)

Sorry to paste a screenshot, happy to paste code

**Comment by jacobrosenthaldfci** [comment]
What is inside the `tile_group`? e.g. what do you see from `list(tile_group.keys())`? To check attributes, you can similarly look at `tile_group.attrs` - what do you see there?

You can see from the documentation [here](https://pathml.readthedocs.io/en/dev/h5path.html#h5path-file-format) that each tile group is supposed to have the following structure, with at most 2 attributes, 2 groups, and 1 dataset:

````
    ├── tile_key1/              (Group)
    │   ├── array               (Dataset, array)
    │   ├── masks/              (Group)
    │   │   ├── mask1           (Dataset, array)
    │   │   ├── mask2           (Dataset, array)
    │   │   └── etc...
    │   ├── coords              (Attribute, tuple)
    │   ├── name                (Attribute, str)
    │   └── labels/             (Group)
    │       ├── label1          (Attribute, [str, int, float, array])
    │       ├── label2          (Attribute, [str, int, float, array])
    │       └── etc...
````

Also, what is the code you used to create the pipeline, run the pipeline, etc.? Posting a minimal working example code snippet to reproduce the error on `tests/testdata/small_vectra.qptiff` would help with the debugging process.

**Comment by surya-narayanan** [comment]
In the `tile_group`, by running `list(tile_group.keys())`, I only see `labels`. 

I will repeat the experiment with the test `qptiff` and get back to you

**Comment by surya-narayanan** [comment]
Update: pipeline seems to work as expected on test qptiff. 

Maybe my save didn't work properly. Will open a new bug with more in-depth info if I find the bug.

**Comment by jacobrosenthaldfci** [comment]
Thanks for the update - definitely feel free to reopen the issue if you keep running into this

**Comment by jacobrosenthaldfci** [comment]
@surya-narayanan one thing that could be causing this is if you saved the h5path file using one version of pathml (e.g. 1.0.3), then install a different version (e.g. dev branch), then try to load it, it might not work if the h5path format has changed between the versions. For example on the dev branch right now we have refactored the h5path format (#231) so this seems like the likely cause of this. So to resolve this try reinstalling the same version of pathml that you used to save the h5path file, or alternatively re-run the pipeline using the new version.

**Comment by surya-narayanan** [comment]
Hmm. While re-running the pipeline on the dev branch, I seem to be running into a wall. Not sure where the error is. I was able to run this pipeline prior

![image](https://user-images.githubusercontent.com/17240858/144931354-adc4c9bd-8fd9-4b46-a214-44aa92aed125.png)

**Comment by jacobrosenthaldfci** [comment]
Can you post a complete code snippet to reproduce this problem on one of the test images? Otherwise, it is pretty difficult to diagnose what is going on without a minimum working example

**Comment by surya-narayanan** [comment]
It works on the `small_vectra` test file, unfortunately :D 

Let me try and debug it some more and I'll get re-open
