### ISSUE TITLE
write_dir argument to slide_dataset incorrect

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#246]
**Describe the bug**
The `write_dir ` argument of `slidedataset.run()`, will pass in whatever parameter was passed in by the user to every call to `slide.run()` from #226

The way it's structured now, will pass in the exact same parameter to every `slide.run()` call

However, this is not correct, since ideally, the parameter should be different for each `slide.run()` call.

**Comment by jacobrosenthaldfci** [comment]
The `write_dir` argument is the directory where slides are written. If using this option, each slide is saved in that directory as <slide name>.h5path:

https://github.com/Dana-Farber-AIOS/pathml/blob/8298747d5b69983d811a0d4a0bfa9300786ba1a1/pathml/core/slide_data.py#L343-L344

The tests here also check to verify that the slides have unique names:

https://github.com/Dana-Farber-AIOS/pathml/blob/8298747d5b69983d811a0d4a0bfa9300786ba1a1/tests/core_tests/test_slide_dataset.py#L38-L54

If you want more fine-grained control over how each h5path file is named, or you want to save slides from a single slide dataset into multiple different directories, then you can always call `SlideData.write()` on individual slides. This is just a convenience feature which writes them all to a single directory with a default naming convention

**Comment by surya-narayanan** [comment]
Got it. Makes sense. Thanks!
