### ISSUE TITLE
Size of .write() call

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#249]
Hi, 

What is the expected size of a .write() call on a slide dataset? For me, a 2T set of vectra images, produced 200 GB of h5 files. From #218 ([comment](_Originally posted by @jacobrosenthaldfci in https://github.com/Dana-Farber-AIOS/pathml/issues/218#issuecomment-956591111_)), I expected 2T of h5 files.

**Comment by jacobrosenthaldfci** [comment]
That was just my intuition, so it could certainly be wrong...
