### ISSUE TITLE
Performance differences between PyPI version and dev branch versions of pathml

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#252]
**Describe the bug**
Processing multiplex immunofluorescence slides with an empty pipeline takes significantly longer on the dev version compared to the PyPI version. 

Using the dev branch, I was only able to process ~20 slides in a day, but the PyPI version was able to do 60 slides in 6 hours.

**Comment by jacobrosenthaldfci** [comment]
Hmm, I'm not sure we'll be able to diagnose what's going on without some more information, including the full code you are using as well as the details of configuration of your machine and information about the images (file formats, sizes, etc.)

We did not see this drop in performance in our benchmarking, the full results of which you can see here: #225 

One possible starting place would be to profile your code and identify where the bottlenecks are
