### ISSUE TITLE
Unable to share h5 files between workers in pytorch dataloader

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#255]
**Describe the bug**
Creating SlideDataset and loading it in a dataloader raises the following error

`KeyError: 'Unable to open object (bad symbol table node signature)'`

Googling it, I realize that this error could be because of sharing h5 files between workers. I will post more about what I find, as I learn more about this error.

**Comment by jacobrosenthaldfci** [comment]
Can you post a complete code snippet to help reproduce this?
We have run the dataloader with multiple workers in the benchmarking suite: https://github.com/Dana-Farber-AIOS/pathml/blob/dfb3d1106bf4339879cab3bd5931854646f1ae32/tests/benchmark/he_benchmark.py#L82-L87 
And did not run into this error

Thanks!

**Comment by surya-narayanan** [comment]
Hmm, I am not sure why- I haven't come across this since, I shall close it for now.
