### ISSUE TITLE
Unable to create a h5 file

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#258]
Getting the error `OSError: Unable to create file (unable to lock file, errno = 11, error message = ‘Resource temporarily unavailable’)` when I try to write a slide to disk. I googled around and heard that the error could be because of permissions issues but I don't think that is the case. I want to post this here in case there are any other users who have the same issue and can pinpoint the cause for the issue.

**Comment by jacobrosenthaldfci** [comment]
Hi Surya, without any code snippets or detailed information about your workflow that is throwing this error, it is hard to tell what is causing this error and whether it is a PathML bug, a problem with your local configuration, and/or a problem with your code.

This thread looks like it may be relevant: https://github.com/h5py/h5py/issues/1066
Do you happen to be writing to a filename that already exists? Or opening the same file multiple times at once?

**Comment by surya-narayanan** [comment]
I think the error was being caused because I am running two programs simultaneously, where one is trying to read an h5 from a folder, and another is trying to write an h5 to the same folder. I think the writing program might have locked the whole folder. 

I solved the problem by changing the writing program to write to a different directory.

**Comment by jacobrosenthaldfci** [comment]
Great! Thanks for posting your solution, hope this can help someone else in the future!
