### ISSUE TITLE
Storing tiles of multiple sizes in the same h5 SlideData object.

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#262]
Is it possible to write SlideData objects that have tiles at multiple resolutions? For example, if I previously wrote a slide to a h5 file with tiles created from a pipeline at 256x256, can I add tiles created at 1024x1024 to the h5 object?

Thanks in advance.

**Comment by ryanccarelli** [comment]
Hi Surya,

When the first tile is added we [store its shape](https://github.com/Dana-Farber-AIOS/pathml/blob/2721cb736599359734ca5ad8bbf7dd66acfc1832/pathml/core/h5managers.py#L148) and [assert that all subsequent tiles have the same shape](https://github.com/Dana-Farber-AIOS/pathml/blob/2721cb736599359734ca5ad8bbf7dd66acfc1832/pathml/core/h5managers.py#L111). We don't use the fact that tiles are the same size anywhere, so this is just a consistency check. Note that we index by coordinate so can't have tiles of multiple sizes at the same base coordinate in one h5path object.

If you needed to do this you could use 2 separate h5path objects, one at each resolution, then concatenate the dataloaders.

**Comment by surya-narayanan** [comment]
Ok. Marking as resolved.
