### ISSUE TITLE
Controlling the resolution of the tiling process

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#264]
**Is your feature request related to a problem? Please describe.**
I am not sure what resolution my tiles are getting created at (40x, 20x, 10x etc.). I would like to have control over this. There seem to be a few efforts along this end- #179 and #191, but I am not sure where they are in deployment. 

Is it possible currently to control the resolution of tiles created in multiplex IF slides?

**Comment by jacobrosenthaldfci** [comment]
You will need to know the magnification of your image to start with - this is something that is sometimes included in the image metadata but not always, so we can't reliably infer it just from the image alone.

Once you know the magnification for the highest resolution, you can use that to infer the magnifications of each level.

If you want to pull a tile at a resolution that is not exactly one of the levels, you can pull a tile from the closest level at a higher magnification and then downsample it using something like `skimage.transform.rescale` to end up at the resolution you want. This is basically what Karen implemented in #191

**Comment by surya-narayanan** [comment]
Cool. Marking as closed. Will re-open if I have any further questions.
