### ISSUE TITLE
Not passing in a client (potentially) causes problems 

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#291]
Program seems to be hanging here, not sure why. Code, screenshot of traceback attached.

```
import sys
from dask.distributed import Client, LocalCluster
from imports import *

#Read in the filepaths 
src = 'Lung_Cancer/mIF/'
slides_names = [path.as_posix() for path in Path(src).rglob('*.qptiff') if 'HnE' not in path.name]  

#Create slides from file paths with a WSI Label for pathology
slides = []
for i in tqdm(slides_names):  
  #Create slide object
  slide = SlideData(i, backend = "bioformats", slide_type = types.Vectra)
  slides.append(slide)

#create a Slide Object
slide_dataset = SlideDataset(slides)

#Create a pipeline
pipeline = Pipeline([
    CollapseRunsVectra(),    
    SegmentMIF(model='mesmer', nuclear_channel=0, cytoplasm_channel=2, image_resolution=0.5, 
               gpu=True, postprocess_kwargs_whole_cell=None, 
               postprocess_kwrags_nuclear=None),
    QuantifyMIF('nuclear_segmentation')   
    ])

cluster = LocalCluster(n_workers=20)
client = Client(cluster)

#Specify where to save the files
write_dir = '/mnt/disks/ip_tiles/ip_slides_pathml/'

#Run and Write
slide_dataset.run(pipeline = pipeline, client = client, write_dir = write_dir, distributed = True)

```

Not able to include traceback as text atm because of some issue, will try asap.
![image](https://user-images.githubusercontent.com/17240858/152887580-f2a75891-f9fb-402b-8032-88a13c28b525.png)

**Comment by jacob-rosenthal** [comment]
Can you post the entire traceback instead of screenshotting part of it?

**Comment by jacob-rosenthal** [comment]
Any clues that gave you the intuition that it's caused by not passing a client object?

**Comment by surya-narayanan** [comment]
i update the issue, even with the client object, the issue persists. This could be related- https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

Working on getting copy of the traceback.

**Comment by surya-narayanan** [comment]
Update- that was the issue, the original issue dissapears if I wrap my code in a `if __name__ == "__main__" block`
