### ISSUE TITLE
Show installation steps on pathml.org

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#292]
Installation steps should be prominent on pathml.org website.

Remove the github buttons from pathml.org too please.

Thank you!

**Comment by surya-narayanan** [comment]
please reconsider removing the github buttons from pathml.org! I find it really useful to navigate to this github from there.

**Comment by Dana-Farber** [comment]
We can keep one button there for sure. Thank you!

**Comment by jacob-rosenthal** [comment]
Done, thank you both!
