### ISSUE TITLE
Not clear how to update a tile

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#300]
Following instructions in #281, I want to update tiles with outputs of a new transform.

My code is as follows.

  ```
pipeline = Pipeline([
      CollapseRunsVectra(),    
      SegmentMIF(model='mesmer', nuclear_channel=0, cytoplasm_channel=2, image_resolution=0.5, 
                postprocess_kwargs_whole_cell=None, 
                postprocess_kwrags_nuclear=None),
      QuantifyMIF('nuclear_segmentation')   
      ])

  
  for i, h5_path in enumerate(h5s):  
    #Create slide object
    h5 = SlideData(h5_path)
    tile_keys = list(h5["tiles"].keys())
    tiles = [h5["tiles"][str(k)]["array"][:] for k in tile_keys]

    for tile in tiles:
      pipeline.apply(tile)
      h5.update(tile) #not sure if this is the right way to do things here

```

I am not able to follow the  [documentation](https://pathml.readthedocs.io/en/latest/api_core_reference.html?highlight=Tiles#pathml.core.Tiles.update) and the code 

https://github.com/Dana-Farber-AIOS/pathml/blob/acaef6c35fa6464f58db62b58b620b722406d80f/pathml/core/tiles.py#L82

I am looking for an update function that takes two arguments, a key and a value, and updates the h5's tiles at the key, with the value. Now, it seems to only take a key object. I am not sure what it updates the tile with.

This would require me to make a new `Tile()` object before updating the `h5`, is that right? 

If I am wrong, please tell me how to update the h5 data with the new tile.

**Comment by ryanccarelli** [comment]
The update function takes a Tile object https://pathml.readthedocs.io/en/latest/api_core_reference.html?highlight=Tiles#pathml.core.Tile

Internally tile.coords is the key.

You can simplify by iterating over SlideData.tiles:
```python3
pipeline = Pipeline([
    CollapseRunsVectra(),    
    SegmentMIF(model='mesmer', nuclear_channel=0, cytoplasm_channel=2, image_resolution=0.5, 
              postprocess_kwargs_whole_cell=None, 
              postprocess_kwargs_nuclear=None),
    QuantifyMIF('nuclear_segmentation')   
    ])

for i, h5_path in enumerate(h5s):  
  #Create slide object
  h5 = SlideData(h5_path)
  for tile in h5.tiles:
    pipeline.apply(tile)
    h5.tiles.update(tile)
```

**Comment by jacob-rosenthal** [comment]
Thanks Surya!
Looking at the code you posted, I wonder if this line might be causing a problem:
> tiles = [h5["tiles"][str(k)]["array"][:] for k in tile_keys]

It seems like this is trying to make a list holding all tiles - which could be a problem if the tiles don't all fit in memory. Perhaps you could try turning it into a generator expression (i.e. `tiles = (h5["tiles"][str(k)]["array"][:] for k in tile_keys)` ) or using the for loop like Ryan suggested, both of which should retrieve tiles lazily one at a time instead of all at once

**Comment by surya-narayanan** [comment]
Yes. I used Ryan's suggestion to get it working. Thanks.
