### ISSUE TITLE
Having PathML work with virtualenv by installing open-slide dependency 

### ISSUE THREAD

**Issue by BeeGass** [Dana-Farber-AIOS/pathml#303]
**Describe the bug**
When using pathml with [virtualenv](https://virtualenv.pypa.io/en/latest/) instead of conda, there is an issue where openslide can not be correctly used straight out of the box. I received this error:
```bash
OSError: libopenslide.so.0: cannot open shared object file: No such file or directory
```

**Suggestion**
I was able to quickly fix the issue by simply installing 
```bash
sudo apt-get install openslide-tools python3-openslide
```
I figured this out via this [comment](https://github.com/openslide/openslide-python/issues/35).

**Additional Comments**
I understand having support for both conda installation and virtualenv might become a bit cumbersome but it looks like it might be simple enough to get virtualenv installation and accompanying instructions up and running. At the very least this may help someone in the future.

**Comment by BeeGass** [comment]
Also had issues with other modules but the fixes were straight forward. I found these were issues for both conda and virtualenv

```bash
pip install deepcell
pip install squidpy
pip3 install bbknn
```

**Comment by jacob-rosenthal** [comment]
Thanks @BeeGass ! Removed bug label since this isn't a bug, and conda installation instructions are still working as expected. For now, conda is still recommended
