### ISSUE TITLE
Dask issue 

### ISSUE THREAD

**Issue by afshinmoradi** [Dana-Farber-AIOS/pathml#315]
Dear, 

I am working at the University of Queensland trying to set the pipeline for spatial IF (CODEX and volumetric slides). Your pipeline looks impressive

I made pathmL work on my laptop with 2 slides. we need to run it on a couple of hundreds of slides every month. But I am getting errors on the HPC cluster. It can be related to the Dask

Could you please confirm that you have already checked the pipeline on HPC? can we run it as a job script? 

I have seen a presentation from your group on Youtube, Shall we have direct contact to set up that?

Your help would be appreciated 

Best regards,

afshin

**Comment by jacob-rosenthal** [comment]
Hi @afshinmoradi , 

Dask supports HPC clusters via [dask-jobqueue](https://jobqueue.dask.org/en/latest/). They support many different types of HPC (PBS, Slurm, MOAB, SGE, LSF, etc.) so you will need to configure based on your specific use case. The dask-jobqueue documentation is the best reference for how to do that - they have examples, etc. But there will likely be some degree of configuration required to get Dask working on the HPC.
Once you have the HPC Dask `Client` object set up, you should be able to pass it as an argument when running a pipeline in PathML. 

I hope this helps point in the right direction - please do keep us updated as I'm sure there are many other people who have similar use cases and could benefit from you sharing your experience with this!
