### ISSUE TITLE
Request to access HoVerNet pre-trained model

### ISSUE THREAD

**Issue by 99snowleopards** [Dana-Farber-AIOS/pathml#319]
**Is your feature request related to a problem? Please describe.**

In the train_hovernet notebook (https://pathml.readthedocs.io/en/latest/examples/link_train_hovernet.html#Conclusion) - you mention that we can load the pre-trained model and test it

**Describe the solution you'd like**

I can't find the notes on loading the pre-trained model,

could you point me to, or share a code snippet to load and test a pre-trained HoVerNet model please?

Thank you!

**Comment by 99snowleopards** [comment]
thank you for replying @jacob-rosenthal , and for sharing the weights - I'm glad to know I wasn't missing any important section in the docs - excited to work with PathML!

**Comment by tddough98** [comment]
What are the nuclear classes for this pretrained model and what order are they in? The most recent version of [PanNuke](https://jgamper.github.io/PanNukeDataset/) has 5 nuclear classes (neoplastic, inflammatory, connective, dead, and epithelial), but this model has 6 nuclear classes. 

The earliest publication listed on the PanNuke site [PanNuke: An Open Pan-Cancer Histology Dataset for Nuclei Instance Segmentation and Classification](https://link.springer.com/chapter/10.1007/978-3-030-23937-4_2) has a table with six classes in this order `Epithelial, Inflam, Malignat, Necrotic, Str, Non-nuclei`, but then has a figure with the classes in this order `Epithelial, Inflam, Malig, Necrotic, NoNuclei, Str` (the last two are switched). I think Str is stroma, which would be connective in the more recent publication?

I see the PathML tutorial filters out class 5 (out of 0-5), which makes me think that the last class is non-nuclear.

**Comment by jacob-rosenthal** [comment]
Hi Tom, this is documented in the PanNuke dataset docs [here](https://pathml.readthedocs.io/en/latest/api_datasets_reference.html#pannuke), not in the HoVer-Net docs, which is probably why it was hard to find. Maybe we could update the tutorial to list the classes to make it easier to follow. 

The classes in order should be:

0. Neoplastic cells
1. Inflammatory
2. Connective/Soft tissue cells
3. Dead Cells
4. Epithelial
5. Background
