### ISSUE TITLE
Error loading multiple slides in pathml

### ISSUE THREAD

**Issue by archanabhardwaj** [Dana-Farber-AIOS/pathml#324]
Hello 
With the help of examples tutorials, all the pre-processing works fine for single slide data. But while loading multiple slides , it gives me error : 

**Here is script that I followed:** 

from pathlib import Path
from pathml.core import HESlide, SlideDataset
data_dir = Path("/DATA/Desktop/AI_pathology/test_AB/")
wsi_paths = list(data_dir.glob("*.svs"))
wsi_paths
wsi_list = [HESlide(p) for p in wsi_paths]

All the above steps are exactly as given in section under "Datasets of Images" at https://pathml.readthedocs.io/en/latest/loading_slides.html 

Error : 
**ArgumentError: argument 1: <class 'TypeError'>: Incorrect type**

If I am missing something, please correct me. 

Thanks in advance

**Comment by jacob-rosenthal** [comment]
Can you please share the full error message?
Can you please also share the output of `print(wsi_paths)`?

**Comment by archanabhardwaj** [comment]
Hello 

I am sharing full error message and exact path : 

from pathlib import Path
from pathml.core import HESlide, SlideDataset
data_dir = Path("/home/Desktop/AI_pathology/test_AB/")
wsi_paths = list(data_dir.glob("*.svs"))


**print(wsi_paths)**
[PosixPath('/home/Desktop/AI_pathology/test_AB/test1.svs'), PosixPath('/home/Desktop/AI_pathology/test_AB/test2.svs')]

Error message : 
wsi_list = [HESlide(p) for p in wsi_paths]

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-36-00425a276c83> in <module>
----> 1 wsi_list = [HESlide(p) for p in wsi_paths]

<ipython-input-36-00425a276c83> in <listcomp>(.0)
----> 1 wsi_list = [HESlide(p) for p in wsi_paths]

~/Desktop/AI_pathology/new_path/pathml/pathml/core/slide_data.py in __init__(self, *args, **kwargs)
    501     def __init__(self, *args, **kwargs):
    502         kwargs["slide_type"] = pathml.core.types.HE
--> 503         super().__init__(*args, **kwargs)
    504 
    505 

~/Desktop/AI_pathology/new_path/pathml/pathml/core/slide_data.py in __init__(self, filepath, name, masks, tiles, labels, backend, slide_type, stain, platform, tma, rgb, volumetric, time_series, counts, dtype)
    161 
    162         if backend.lower() == "openslide":
--> 163             backend_obj = pathml.core.OpenSlideBackend(filepath)
    164         elif backend.lower() == "bioformats":
    165             backend_obj = pathml.core.BioFormatsBackend(filepath, dtype)

~/Desktop/AI_pathology/new_path/pathml/pathml/core/slide_backends.py in __init__(self, filename)
     63         logger.info(f"OpenSlideBackend loading file at: {filename}")
     64         self.filename = filename
---> 65         self.slide = openslide.open_slide(filename=filename)
     66         self.level_count = self.slide.level_count
     67 

~/.local/lib/python3.8/site-packages/openslide/__init__.py in open_slide(filename)
    386     object for other types of images."""
    387     try:
--> 388         return OpenSlide(filename)
    389     except OpenSlideUnsupportedFormatError:
    390         return ImageSlide(filename)

~/.local/lib/python3.8/site-packages/openslide/__init__.py in __init__(self, filename)
    158         AbstractSlide.__init__(self)
    159         self._filename = filename
--> 160         self._osr = lowlevel.open(filename)
    161 
    162     def __repr__(self):

ArgumentError: argument 1: <class 'TypeError'>: Incorrect type

Thanks in advance

**Comment by jacob-rosenthal** [comment]
Great, posting the entire error message is very useful! 

Looks like the problem is being caused because the paths in `wsi_paths` are Pathlib.Path objects, which openslide doesn't know how to open (https://github.com/openslide/openslide-python/issues/112). They did update openslide to fix this in v1.2.0 (https://github.com/openslide/openslide-python/pull/123, mentioned in [release notes](https://github.com/openslide/openslide-python/blob/main/CHANGELOG.md#version-120-2022-06-17)). 

So, I think there are two ways you could fix this:
1. convert the Path objects to strings first (`wsi_list = [HESlide(str(p)) for p in wsi_paths]`)
2. Update openslide to v1.2.0 or greater

We can also add a check in PathML to prevent this from happening in the future. Thanks!!

**Comment by archanabhardwaj** [comment]
Hi 
I converted the converted the Path objects to strings and it worked. 

Thanks!!
