### ISSUE TITLE
docs.pathml.org is down

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#327]
https://docs.pathml.org/ does not link to https://pathml.readthedocs.io/en/latest/

**Comment by jacob-rosenthal** [comment]
Domain forwarding doesn't work with https. See [here](https://community.godaddy.com/s/question/0D53t00006VmW1RCAV/forwarding-from-https). The redirect is working normally using http://docs.pathml.org. When sharing the link please make sure to use the http link.

**Comment by Dana-Farber** [comment]
Please get and install the SSL cert so the https will work too. Thank you!!
