### ISSUE TITLE
SegmentMIF Assertion error issue

### ISSUE THREAD

**Issue by ckv1110** [Dana-Farber-AIOS/pathml#328]
Hi, I have started PathML recently, and I am trying to use the SegmentMIF preprocessing transform to segment nuclei in my HnE images. My HnE slide is in the .svs format. Before I applied the SegmentMIF preprocessing, I used the StainNormalizationHE transform.

However, when running the transform, I ran into an Assertion Error, where it received the slide_type of 'HE', but it requires the slide_type  of 'Fluor'. I tried changing slide_type into 'Fluor' just to see if it would change anything, but it still runs into an Assertion Error, where it received the 'Fluor' slide_type but needs the 'HE' slide_type. The screenshots of the errors can be seen below.

As I am quite new with python and PathML, I'm unsure where I went wrong and how I can fix the issue. I'm posting this as an issue to seek an understanding of this issue and how I can fix it. Thank you very much for your time.

![Screenshot from 2022-08-11 13-36-44](https://user-images.githubusercontent.com/65700894/185825124-9e1f712f-8de0-4ad9-866a-0de2b30ab63b.png)
![Screenshot from 2022-08-11 13-41-25](https://user-images.githubusercontent.com/65700894/185825098-6f953f9f-f9b7-4130-a4a6-bd803305eddc.png)

**Comment by jacob-rosenthal** [comment]
The "MIF" part in "SegmentMIF" is for Multiplex ImmunoFluorescence. So the segmentation methods in those models probably aren't applicable to your H&E images. For example, to use the mesmer model, you need to supply one channel for the nucleus marker and another channel for the cytoplasm marker - but for H&E images you only have white light so the channels are just RGB.

That said, the slide type should be set while loading the SlideData object initially. When tiles are generated, each tile is just assigned the slide_type from the parent SlideData (see below for exact line where this happens): https://github.com/Dana-Farber-AIOS/pathml/blob/adb6a0acf3d03681ef1c083dbe68b89d5c1982a7/pathml/core/slide_data.py#L429-L431

**Comment by ckv1110** [comment]
Thank you so much for helping me understand my issue! I'll close the issue now.
