### ISSUE TITLE
indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by luzy05111036** [Dana-Farber-AIOS/pathml#341]
**Describe the bug**
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (CPU)

**To Reproduce**

n_classes_pannuke = 6

### load the model
hovernet = HoVerNet(n_classes=n_classes_pannuke)

### wrap model to use multi-GPU
hovernet = torch.nn.DataParallel(hovernet)

### set up optimizer
opt = torch.optim.Adam(hovernet.parameters(), lr = 1e-4)
### learning rate scheduler to reduce LR by factor of 10 each 25 epochs
scheduler = StepLR(opt, step_size=25, gamma=0.1)

### send model to GPU
hovernet.to(device);

n_epochs = 50

### print performance metrics every n epochs
print_every_n_epochs = None

### this saves time instead of evaluating on the entire validation set
n_minibatch_valid = 50

epoch_train_losses = {}
epoch_valid_losses = {}
epoch_train_dice = {}
epoch_valid_dice = {}

best_epoch = 0

### main training loop
for i in tqdm(range(n_epochs)):
    minibatch_train_losses = []
    minibatch_train_dice = []

    ### put model in training mode
    hovernet.train()

    for data in train_dataloader:
        ### send the data to the GPU
        images = data[0].float().to(device)
        masks = data[1].to(device)
        hv = data[2].float().to(device)
        tissue_type = data[3]

        ### zero out gradient
        opt.zero_grad()

        ### forward pass
        outputs = hovernet(images)

        ### compute loss
        loss = loss_hovernet(outputs = outputs, ground_truth = [masks, hv], n_classes=6)

        ### track loss
        minibatch_train_losses.append(loss.item())

        ### also track dice score to measure performance
        preds_detection, preds_classification = post_process_batch_hovernet(outputs, n_classes=n_classes_pannuke)
        truth_binary = masks[:, -1, :, :] == 0
        dice = dice_score(preds_detection, truth_binary.cpu().numpy())
        minibatch_train_dice.append(dice)

        ### compute gradients
        loss.backward()

        ### step optimizer and scheduler
        opt.step()

    ### step LR scheduler
    scheduler.step()

    ### evaluate on random subset of validation data
    hovernet.eval()
    minibatch_valid_losses = []
    minibatch_valid_dice = []
    ### randomly choose minibatches for evaluating
    minibatch_ix = np.random.choice(range(len(valid_dataloader)), replace=False, size=n_minibatch_valid)
    with torch.no_grad():
        for j, data in enumerate(valid_dataloader):
            if j in minibatch_ix:
                # send the data to the GPU
                images = data[0].float().to(device)
                masks = data[1].to(device)
                hv = data[2].float().to(device)
                tissue_type = data[3]

                # forward pass
                outputs = hovernet(images)

                # compute loss
                loss = loss_hovernet(outputs = outputs, ground_truth = [masks, hv], n_classes=6)

                # track loss
                minibatch_valid_losses.append(loss.item())

                # also track dice score to measure performance
                preds_detection, preds_classification = post_process_batch_hovernet(outputs, n_classes=n_classes_pannuke)
                truth_binary = masks[:, -1, :, :] == 0
                dice = dice_score(preds_detection, truth_binary.cpu().numpy())
                minibatch_valid_dice.append(dice)

    ### average performance metrics over minibatches
    mean_train_loss = np.mean(minibatch_train_losses)
    mean_valid_loss = np.mean(minibatch_valid_losses)
    mean_train_dice = np.mean(minibatch_train_dice)
    mean_valid_dice = np.mean(minibatch_valid_dice)

    ### save the model with best performance
    if i != 0:
        if mean_valid_loss < min(epoch_valid_losses.values()):
            best_epoch = i
            torch.save(hovernet.state_dict(), f"hovernet_best_perf.pt")

    ### track performance over training epochs
    epoch_train_losses.update({i : mean_train_loss})
    epoch_valid_losses.update({i : mean_valid_loss})
    epoch_train_dice.update({i : mean_train_dice})
    epoch_valid_dice.update({i : mean_valid_dice})

    if print_every_n_epochs is not None:
        if i % print_every_n_epochs == print_every_n_epochs - 1:
            print(f"Epoch {i+1}/{n_epochs}:")
            print(f"\ttraining loss: {np.round(mean_train_loss, 4)}\tvalidation loss: {np.round(mean_valid_loss, 4)}")
            print(f"\ttraining dice: {np.round(mean_train_dice, 4)}\tvalidation dice: {np.round(mean_valid_dice, 4)}")

### save fully trained model
torch.save(hovernet.state_dict(), f"hovernet_fully_trained.pt")
print(f"\nEpoch with best validation performance: {best_epoch}")

**Expected behavior**
Should start model training

**Screenshots**
![image](https://user-images.githubusercontent.com/70253071/205712867-3eb17f41-9eb4-4905-bf42-a153dbb1dcfe.png)

**Additional context**
Anyone else also have this problem. I run this on HPC with 4 GPUs, each having 16G memory.

**Comment by WilliWespe** [comment]
Yes, I did something similar to this. I my case I explicitly wanted the computations to be on the gpu. I edited the `utils.py` file in the pathml package like this:

In **line 73** write:` true_1_hot = torch.eye(num_classes + 1).to('cuda:0')[true.squeeze(1)]`

You also have to add` .to('cuda:0')` to the tensor in **line 84 (the else block)**.

Until now the program runs. I couldn't test a full training so far, because it needs to long. But the outer for loop ran for two iterations without error.

**Comment by WilliWespe** [comment]
Well, in my case i first changed my directory to `miniconda3/envs/py38/lib/python3.8/site-packages/pathml/ml`.
Then I opened `utils.py` with `nano` and edited/saved it. After that restart your notebook.

Was this your question?

**Comment by luzy05111036** [comment]
@WilliWespe thanks. Yes, that's my question and it works. I am starting training now.

**Comment by luzy05111036** [comment]
problem solved

**Comment by FerranC96** [comment]
Thank you all for the discussion above!
Can confirm the patch above still works in 2024 with `pathml 2.1.1`
