### ISSUE TITLE
preprocessing on mrxs file get h5 file full of 0

### ISSUE THREAD

**Issue by YubinXie** [Dana-Farber-AIOS/pathml#344]
**Describe the bug**
I ran the preprocessing pipeline as the tutorial and i got an output full of 0 h5.
 
**To Reproduce**
List the exact steps to reproduce the behavior.
```
pipeline = Pipeline([
    BoxBlur(kernel_size=15),
    TissueDetectionHE(mask_name = "tissue", min_region_size=100, threshold=None, outer_contours_only=True)
])

wsi.run(pipeline,level=1,write_dir='xxx')

```
**Expected behavior**
H5 file with tiles of data 

Am I missing anything here? I can see my slides with content under openslides. I dont know if there is something wrong - format or other thing causing this issue.

**Comment by jacob-rosenthal** [comment]
Can you check if the backend is working? i.e. does `extract_region()` return the correct images?

**Comment by YubinXie** [comment]
> Can you check if the backend is working? i.e. does `extract_region()` return the correct images?

Hi Jacob! Thanks for your timely reply. I just found it was not all black. There are some real images. I think I must be confused on how the pipeline works and how the data is stored. The resulted h5 file from the pipeline has some real images but it is unclear to me how to find them. Is there a filter function? What is the best document for me to check this. I read all the tutorials and they are fairly simple and it did not mention these details. Many thanks!

**Comment by jacob-rosenthal** [comment]
Great, glad to hear that. I'll remove the bug label then.

When a pipeline is run, all the tiles will be extracted and put into h5. So depending on the tile size, you could end up with some blank tiles - for example, around the edges of the whole slide image, where there's no tissue and it's just blank. 
One thing you could do next is try filtering out all the empty tiles. After running the pipeline and populating `wsi.tiles`, you can just loop through wsi.tiles and for each tile, check whether to keep it or not (e.g. based on pixel values, or the tile mask from tissue detection, etc.) and delete the tiles you don't want. 

Hope this is helpful or at least points in the right direction!

**Comment by YubinXie** [comment]
Thanks Jacob. The plan sounds good. One issue I noticed is that in my pipeline I have TissueDetectionHE(mask_name = "tissue") and the resulting data actually has 0 masks in it. Do you know what could be the issue? I'd like to filter out the non-tissue tiles based on this.

**Comment by jacob-rosenthal** [comment]
Each tile should have a mask, which can be accessed by e.g. `wsi.tiles[0].masks["tissue"]`

**Comment by YubinXie** [comment]
You are right! I thought it is on wsi tissue level. Obviously it is in pixel level within each tile. Thank you. All look great now!
