### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by jacob-rosenthal** [Dana-Farber-AIOS/pathml#353]
Tests have started failing in GitHub actions.
Even tests which [passed](https://github.com/Dana-Farber-AIOS/pathml/actions/runs/5006772459) 5 days ago, now [fail](https://github.com/Dana-Farber-AIOS/pathml/actions/runs/5051829941) today.
Need to figure out what is going wrong with the GitHub actions workflows, and fix

**Comment by sreekarreddydfci** [comment]
PR #354 should fix this issue.

**Comment by jacob-rosenthal** [comment]
Great. Thanks!
