### ISSUE TITLE
add Digital Pathology Assistant notebook

### ISSUE THREAD

**Issue by Dana-Farber** [Dana-Farber-AIOS/pathml#431]
add Digital Pathology Assistant notebook. Queries should be, in this order:
How to install...
How to create H&E analysis...
How to create mIF analysis...
How to create graph...
How to use Inference API ....

Please link it to the main README.md page, updating the Examples section,  and also in the examples/README.md.  Please also update the readthedocs to have a link to the notebook and to the AI. The updated link is in the manuscript. Thank you!

**Comment by Dana-Farber** [comment]
@achowdhury364 and @VarunUllanat  please merge this into 3.0. Thank you!

**Comment by VarunUllanat** [comment]
Addressed in PR #432
